--  create users
create table USERS (id INTEGER primary key, username VARCHAR(255));

create table IXP_MONITORING_DATA(
    IXP VARCHAR(255),
    COUNTRY VARCHAR(64),
    CITY VARCHAR(64),
    RS_LOCAL_ASN INTEGER,
    NUMBER_OF_RIB_ENTRIES INTEGER,
    NUMBER_OF_PEERS INTEGER,
    TOTAL_NUMBER_OF_NEIGHBORS INTEGER,
    UPDATED TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (IXP, COUNTRY, CITY)
);

create table IXP_MONITORING_DATA_V2(
    IXP VARCHAR(255),
    COUNTRY VARCHAR(64),
    CITY VARCHAR(64),
    RS_LOCAL_ASN INTEGER,
    NUMBER_OF_RIB_ENTRIES INTEGER,
    NUMBER_OF_PEERS INTEGER,
    TOTAL_NUMBER_OF_NEIGHBORS INTEGER,
    UPDATED TIMESTAMP WITHOUT TIMESTAMP,
    PRIMARY KEY (IXP, COUNTRY, CITY)
);